config/routes.rb
GoTrack::Application.routes.draw do
  devise_for :user

  root to: 'home#index'

  get '/login', to: 'home#index'

  devise_scope :user do
    get '/user/sign_out', to: 'devise/sessions#destroy'
  end

  get '/set_ui_version' => 'application#set_ui_version', as: 'set_ui_version'
  get 'home' => 'home#index'
  get 'render_confirmation_modal' => 'application#render_confirmation_modal'

  get 'home/dispatch' => 'home#dispatch_device' # NOTE - dispatch needs to be changed to dispatch_device to avoid global name conflict
  post 'home/dispatch' => 'home#dispatch_device'

  get 'home/:action' => 'home'

  post '/home/act_as_if_account' => 'home#act_as_if_account'

  get '/geocoded_locations', to: 'locations#search_readings_location'

  resources :groups

  resources :devices, except: %i(new create show) do
    collection do
      post :search_devices
      post :choose_mt
    end
  end

  get 'reports' => 'reports#index'
  get 'reports/:action(/:id)' => 'reports', id: /\d+/, as: :action_reports

  resources :users, except: %i(show)

  resources :contact do
    collection do
      get :index
      post :thanks
    end
  end

  get 'settings' => 'settings#index'
  post 'settings' => 'settings#submit'

  get 'readings/:action(/:id)' => 'readings'

  namespace :api do
    post 'messages/send_messages' => 'messages#send_messages'
  end

  get 'admin_status/:action(/:id)' => 'admin_status'

  resources :scheduled_reports do
    member do
      get :download
    end
  end

  resources :geofences do
    collection do
      get :for_device
    end
  end

  get 'utils/:action(/:id)' => 'utils'
  get 'simulator' => 'simulator#index'
  get 'simulator/insert_reading' => 'simulator#insert_reading'

  resources :maintenances, except: %i(edit update) do
    member do
      post :reset
      get :reset
      post :complete
    end
  end

  namespace :admin do
    root to: 'overview#index'
    post :set_login_message, to: 'overview#set_login_message'
    get 'toggle_login_message', to: 'overview#toggle_login_message'

    resources :accounts, constraints: { id: /\d+/ } do
      collection do
        get '/search' => 'accounts#search'
      end
    end

    resources :device_profiles, constraints: { id: /\d+/ }

    resources :devices, constraints: { id: /\d+/ } do
      collection do
        get :digital_sensor_form
        get '/search' => 'devices#search'
        get '/clear_history' => 'devices#clear_history'
        get '/on_change_gateway_get_device_types' => 'devices#on_change_gateway_get_device_types'
      end
    end

    resources :users, except: [:show], constraints: { id: /\d+/ } do
      collection do
        get '/search' => 'users#search'
      end
    end
  end

  resources :devices do
    resources :test_readings, only: %i(new create)
  end

  resources :one_time_reports, only: %i(new create)
end

app/helpers/layout_helper.rb
module LayoutHelper
  def javascript(*args)
    args = args.map { |arg| arg == :defaults ? arg : arg.to_s }
    content_for(:head) { javascript_include_tag(args, cache: "#{args.join('_')}_cached") }
  end
end

app/views/layouts/includes/_footer.html.erb
<% if request.server_name.is_a? String %>
	<% if request.server_name.index("gotrack.com") %>
	  <script type="text/javascript">
	    var _gauges = _gauges || [];
	    (function() {
	      var t   = document.createElement('script');
	      t.type  = 'text/javascript';
	      t.async = true;
	      t.id    = 'gauges-tracker';
	      t.setAttribute('data-site-id', '4f2d2de7844d520610000018');
	      t.src = '//secure.gaug.es/track.js';
	      var s = document.getElementsByTagName('script')[0];
	      s.parentNode.insertBefore(t, s);
	    })();
	  </script>
	<% elsif request.server_name.index("mrpbx.com") %>
	  <script type="text/javascript">
	    var _gauges = _gauges || [];
	    (function() {
	      var t   = document.createElement('script');
	      t.type  = 'text/javascript';
	      t.async = true;
	      t.id    = 'gauges-tracker';
	      t.setAttribute('data-site-id', '4f2d2f1dcb25bc2f34000016');
	      t.src = '//secure.gaug.es/track.js';
	      var s = document.getElementsByTagName('script')[0];
	      s.parentNode.insertBefore(t, s);
	    })();
	  </script>
	<% end %>
<% end %>

app/views/layouts/includes/_header.html.erb
<% page_name = controller.controller_name %>

<% if browser.device.mobile? %>
  <div class="header-mobile">
    <ul>
      <li <% if page_name == 'home'%> class="selected-menu-tab"<% end %> "><%= link_to home_path do %><span>Overview</span><% end %></li>
      <li <% if page_name == "reports" %> class="selected-menu-tab"<% end %>><%= link_to action_reports_path(action: :all) do %><span>Reports</span><% end %></li>
      <li> <%= link_to destroy_user_session_path do %><span>Logout</span><% end %></li>
    </ul>
  </div>
<% else %>
  <div class="header">
    <div class="header-top">
      <div class="header-top__left">
        <div class="gotrack-logo">
          <%= render partial: 'shared/gotrack_logo' %>
        </div>

        <div class="vertical-separator"></div>

        <div class="company" ><%= current_account.try(:company) || @page_title %></div>
      </div>

      <div class="header-top__right">
        <% if current_user %>
          <div class="logged-user">
            <div class="user-name">
              <div class="user-name__icon">
                <%= fa_icon "user lg" %>
              </div>
              <div class="user-name__text">
                <%= current_user.full_name %>
              </div>
              <div class="user-name__options-icon">
                <%= fa_icon "caret-down lg" %>
              </div>
              <div class="user-options user-options--hidden">
                <nav>
                  <ul>
                    <% if current_user.is_super_admin? %>
                      <% if request.original_url.include?('admin') %>
                        <div class="user-option">
                          <li>
                            <a href="/">
                              <%= fa_icon "lock", class: "user-option__icon" %>
                              Exit admin
                            </a>
                          </li>
                        </div>
                      <% else %>
                        <div class="user-option">
                          <li>
                            <a href="/admin">
                              <%= fa_icon "unlock-alt", class: "user-option__icon" %>
                              Admin
                            </a>
                          </li>
                        </div>
                      <% end %>
                    <% end %>
                    <div class="user-option">
                      <li>
                        <%= link_to destroy_user_session_path do %>
                          <%= fa_icon "sign-out", class: "user-option__icon" %>
                          Logout
                        <% end %>
                      </li>
                    </div>
                  </ul>
                </nav>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>

    <% if current_user %>
      <div class="header-bottom">
        <% if current_user.is_super_admin? && request.original_url.include?('admin') %>
          <%= render partial: "layouts/admin/header/nav_tabs" %>
        <% else %>
          <%= render partial: "layouts/includes/header/nav_tabs" %>
        <% end %>
      </div>
    <% end %>
  </div>

  <% if current_user && current_user.is_super_admin? && request.original_url.include?('admin') %>
    <%= render partial: "layouts/admin/header/subnav" %>
  <% end %>

  <%= javascript_include_tag "header" %>
<% end %>

app/views/layouts/includes/_map_key.erb
<script type="text/javascript" src="<%= request.protocol %>maps.googleapis.com/maps/api/js?v=3.31&region=US&key=<%= GOOGLE_MAPS_API_KEY %>"></script>

app/views/layouts/includes/_select_group_or_device.html.erb
<% select_onchange ||= nil %>
<% select_class ||= nil %>
	<select id="group_type"<% if select_class %> class="<%= select_class %>"<% end %> name="<%= select_name %>"<% if select_onchange %> onchange="<%= select_onchange %>;"<% end %>>
		<option value="all" <%if current_group_value == 'all' and not current_home_device %> selected class="default-row"<%end%>>All Fleets</span>
		<% for group in all_groups %>
			<option <%if current_group_value.to_i == group.id and not current_home_device %> selected class="default-row"<%end%> value='<%= group.id%>'><%= group.name %></option>
		<% end %>
		<%if default_devices.any? %>
			<option <%if current_group_value == 'default' %> selected class="default-row" <%end%> value='default'>Default</option>
		<%end%>
		<option id="" disabled="disabled"> - - - - - - - - - - - - - - -  </option>
		<% for device in all_devices %>
			<option <%if current_home_device.to_i == device.id %> selected class="default-row"<%end%> value='<%= -device.id %>'><%= device.name %></option>
		<% end %>
	</select>
	<i class="fa fa-caret-down form-select__arrow search-bar__arrow" aria-hidden="true"></i>

app/views/layouts/includes/_switch_account.html.erb
<%#TODO:  decide if this template should get tossed out the window %>
<!-- 
<%# if current_user.is_super_admin? && current_user.accessible_account_ids.size > 1 %>
    <strong>View different account: </strong>
    <%#= form_tag :home_act_as_if_account, {id: 'act-as-if-account-form', class: 'act-as-if-account-form'} do %>
        <select id="current-account-id" >
          <%# current_account_id = current_account.id.blank? ? current_user.account_id : current_account.id.to_i %>
          <%# Account.where(id: current_user.accessible_account_ids).each do |account| %>
              <option value="<%#= account.id %>" <%#= 'selected="selected"' if current_account_id == account.id %>>
                <%#= account.company %>
              </option>
          <%#  end %>
        </select>
        <%#= hidden_field_tag :redirect_to, path %>
        <%#= hidden_field_tag :new_account_id, current_account.id %>
    <%# end %>
<%# end %>
-->