config/routes.rb
GoTrack::Application.routes.draw do
  devise_for :user

  root to: 'home#index'

  get '/login', to: 'home#index'

  devise_scope :user do
    get '/user/sign_out', to: 'devise/sessions#destroy'
  end

  get '/set_ui_version' => 'application#set_ui_version', as: 'set_ui_version'
  get 'home' => 'home#index'
  get 'render_confirmation_modal' => 'application#render_confirmation_modal'

  get 'home/dispatch' => 'home#dispatch_device' # NOTE - dispatch needs to be changed to dispatch_device to avoid global name conflict
  post 'home/dispatch' => 'home#dispatch_device'

  get 'home/:action' => 'home'

  post '/home/act_as_if_account' => 'home#act_as_if_account'

  get '/geocoded_locations', to: 'locations#search_readings_location'

  resources :groups

  resources :devices, except: %i(new create show) do
    collection do
      post :search_devices
      post :choose_mt
    end
  end

  get 'reports' => 'reports#index'
  get 'reports/:action(/:id)' => 'reports', id: /\d+/, as: :action_reports

  resources :users, except: %i(show)

  resources :contact do
    collection do
      get :index
      post :thanks
    end
  end

  get 'settings' => 'settings#index'
  post 'settings' => 'settings#submit'

  get 'readings/:action(/:id)' => 'readings'

  namespace :api do
    post 'messages/send_messages' => 'messages#send_messages'
  end

  get 'admin_status/:action(/:id)' => 'admin_status'

  resources :scheduled_reports do
    member do
      get :download
    end
  end

  resources :geofences do
    collection do
      get :for_device
    end
  end

  get 'utils/:action(/:id)' => 'utils'
  get 'simulator' => 'simulator#index'
  get 'simulator/insert_reading' => 'simulator#insert_reading'

  resources :maintenances, except: %i(edit update) do
    member do
      post :reset
      get :reset
      post :complete
    end
  end

  namespace :admin do
    root to: 'overview#index'
    post :set_login_message, to: 'overview#set_login_message'
    get 'toggle_login_message', to: 'overview#toggle_login_message'

    resources :accounts, constraints: { id: /\d+/ } do
      collection do
        get '/search' => 'accounts#search'
      end
    end

    resources :device_profiles, constraints: { id: /\d+/ }

    resources :devices, constraints: { id: /\d+/ } do
      collection do
        get :digital_sensor_form
        get '/search' => 'devices#search'
        get '/clear_history' => 'devices#clear_history'
        get '/on_change_gateway_get_device_types' => 'devices#on_change_gateway_get_device_types'
      end
    end

    resources :users, except: [:show], constraints: { id: /\d+/ } do
      collection do
        get '/search' => 'users#search'
      end
    end
  end

  resources :devices do
    resources :test_readings, only: %i(new create)
  end

  resources :one_time_reports, only: %i(new create)
end

app/views/notifier/app_feedback.html.erb
Sender: <%= @sender %>
When: <%= Time.now %>
Feedback: <%= @feedback %>

app/views/notifier/change_password.html.erb
Dear <%= @name %>,

At your request, <%= @app_name %> has changed your password. If it was not at your request, then you should be aware that someone has access to your account and requested this change.

<%= @url %>

app/views/notifier/device_offline.html.erb
Dear <%= @name %>,

<%= @device_name %> seems to be offline. This device last communicated <%= time_ago_in_words @last_online %> ago.

app/views/notifier/forgot_password.html.erb
Dear <%= @name %>,

At your request, <%= @app_name %> has sent you the following URL so that you may reset your password. If it was not at your request, then you should be aware that someone has entered your email address as theirs in the forgotten password section of <%= @app_name %>.

Please click on the following link to go to the change password page:

<%= @url %>

app/views/notifier/movement_alert.text.erb
Dear <%= @alert.user.first_name %> <%= @alert.user.last_name %>,

EZ-Alert Instant next movement notification for device <%= @alert.device.name %> on <%= @display_time %>.

app/views/notifier/notify_reading.html.erb
Dear <%= @name %>,

<%= @device_name %> <%= @action %> at <%= @display_time%>

app/views/notifier/notify_task.html.erb
Dear <%= @name %>,<br />
<br />
<%= @device_name %> <%= @action %> at <%= @display_time%>.<br />
<br />
You can mark this task as completed by logging in to GoTrack and clicking
<%= link_to 'this link', maintenance_url(@task_id) %>