config/routes.rb
GoTrack::Application.routes.draw do
  devise_for :user

  root to: 'home#index'

  get '/login', to: 'home#index'

  devise_scope :user do
    get '/user/sign_out', to: 'devise/sessions#destroy'
  end

  get '/set_ui_version' => 'application#set_ui_version', as: 'set_ui_version'
  get 'home' => 'home#index'
  get 'render_confirmation_modal' => 'application#render_confirmation_modal'

  get 'home/dispatch' => 'home#dispatch_device' # NOTE - dispatch needs to be changed to dispatch_device to avoid global name conflict
  post 'home/dispatch' => 'home#dispatch_device'

  get 'home/:action' => 'home'

  post '/home/act_as_if_account' => 'home#act_as_if_account'

  get '/geocoded_locations', to: 'locations#search_readings_location'

  resources :groups

  resources :devices, except: %i(new create show) do
    collection do
      post :search_devices
      post :choose_mt
    end
  end

  get 'reports' => 'reports#index'
  get 'reports/:action(/:id)' => 'reports', id: /\d+/, as: :action_reports

  resources :users, except: %i(show)

  resources :contact do
    collection do
      get :index
      post :thanks
    end
  end

  get 'settings' => 'settings#index'
  post 'settings' => 'settings#submit'

  get 'readings/:action(/:id)' => 'readings'

  namespace :api do
    post 'messages/send_messages' => 'messages#send_messages'
  end

  get 'admin_status/:action(/:id)' => 'admin_status'

  resources :scheduled_reports do
    member do
      get :download
    end
  end

  resources :geofences do
    collection do
      get :for_device
    end
  end

  get 'utils/:action(/:id)' => 'utils'
  get 'simulator' => 'simulator#index'
  get 'simulator/insert_reading' => 'simulator#insert_reading'

  resources :maintenances, except: %i(edit update) do
    member do
      post :reset
      get :reset
      post :complete
    end
  end

  namespace :admin do
    root to: 'overview#index'
    post :set_login_message, to: 'overview#set_login_message'
    get 'toggle_login_message', to: 'overview#toggle_login_message'

    resources :accounts, constraints: { id: /\d+/ } do
      collection do
        get '/search' => 'accounts#search'
      end
    end

    resources :device_profiles, constraints: { id: /\d+/ }

    resources :devices, constraints: { id: /\d+/ } do
      collection do
        get :digital_sensor_form
        get '/search' => 'devices#search'
        get '/clear_history' => 'devices#clear_history'
        get '/on_change_gateway_get_device_types' => 'devices#on_change_gateway_get_device_types'
      end
    end

    resources :users, except: [:show], constraints: { id: /\d+/ } do
      collection do
        get '/search' => 'users#search'
      end
    end
  end

  resources :devices do
    resources :test_readings, only: %i(new create)
  end

  resources :one_time_reports, only: %i(new create)
end

app/controllers/admin/overview_controller.rb
class Admin::OverviewController < ApplicationController
  unloadable # making unloadable per http://dev.rubyonrails.org/ticket/6001
  before_filter :authorize_super_admin
  layout 'admin'

  def index
    @current_user = current_user
    @total_accounts = Account.count
    @total_users = User.count
    @total_devices = Device.provisioned.count
    @total_device_profiles = DeviceProfile.count
  end

  def set_login_message
    if params[:login_message] && params[:login_message][:message]
      LoginMessage.instance.update_attribute(:message, params[:login_message][:message])
    end

    redirect_to :admin_root
  end

  def toggle_login_message
    msg = LoginMessage.instance
    msg.update_attribute(:is_active, !msg.is_active?)
  end
end

app/views/admin/overview/_login_message_active.html.erb
<% active = LoginMessage.instance.is_active? %>
<% text_class = active ? 'login-message__status-active' : 'login-message__status-inactive' %>
<% message = active ? 'Active' : 'Inactive' %>
<% text = active ? 'Deactivate' : 'Activate'  %>

<input type="button" class="button button--primary button--inline" value="<%= text %>" onclick="$.ajax({ url: '/admin/toggle_login_message', dataType: 'script' })" />
<span class="login-message <%= text_class %>">Currently <b><%= message %></b></span>

app/views/admin/overview/_login_message_preview.html.erb
<div id="special_message" class="login-message-preview">
  <div id="login_message_content" class="login-message-preview__text login-message-preview__static-text"><%= LoginMessage.instance.to_html %></div>
  <div class="form-row form-row--flex">
    <% if LoginMessage.instance.persisted? %>
      <div class="login-message__last-edited">last edited <%= LoginMessage.instance.updated_at.in_time_zone(current_user.time_zone).strftime('%b %d, %Y') %></div>
    <% end %>
    <a class="button button--primary button--large login-message-preview__edit-btn" onclick="showLoginMessageForm()">Edit</a>
  </div>
</div>

<%= form_tag(admin_set_login_message_path, { id: :login_message_form, class: 'special_message login-message-preview', style: 'display: none;' }) do %>
	<textarea name="login_message[message]" class="login-message-preview__text"><%= LoginMessage.instance.message %></textarea>
  <div class="form-row form-row--flex">
    <div class="form-row form-row--inline form-row--actions">
      <a class="login-message-preview__help" target="_blank" href="http://en.wikipedia.org/wiki/HTML#Element_examples">Formatting help</a>
      <input class="button button--primary button--large button--inline button--right" type="submit" value="Update" onclick='return(confirm("Are you sure?"))' />
      <a class="button button--secondary button--inline button--right" href="javascript:hideLoginMessageForm();">Cancel</a>
    </div>
  </div>
<% end %>

app/views/admin/overview/index.html.erb
<div class="admin-overview">

  <div class="page-title admin-overview__title">Admin Overview</div>

  <div class="admin-overview__summary">
    <div class="admin-overview-box">
      <div class="admin-overview-box__content">
        <a href="/admin/accounts">
          <div class="admin-overview-box__title">Accounts</div>
          <div class="admin-overview-box__value"><%= @total_accounts %></div>
        </a>
        <div class="admin-overview-box__action">
          <a href="/admin/accounts/new" class="button button--primary">Create</a>
        </div>
      </div>
    </div>

    <div class="admin-overview-box">
      <div class="admin-overview-box__content">
        <a href="/admin/users">
          <div class="admin-overview-box__title">Users</div>
          <div class="admin-overview-box__value"><%= @total_users %></div>
        </a>
        <div class="admin-overview-box__action">
          <a href="/admin/users/new" class="button button--primary">Create</a>
        </div>
      </div>
    </div>

    <div class="admin-overview-box">
      <div class="admin-overview-box__content">
        <a href="/admin/devices">
          <div class="admin-overview-box__title">Devices</div>
          <div class="admin-overview-box__value"><%= @total_devices %></div>
        </a>
        <div class="admin-overview-box__action">
          <a href="/admin/devices/new" class="button button--primary">Create</a>
        </div>
      </div>
    </div>
  </div>

  <% if !current_user.nil? && current_user.is_super_admin? %>
    <div class="admin-overview__login-message">
      <div class="page-title admin-overview__title">Login Message</div>
      <div id="login_message_active" class="admin-overview__login-message-header">
        <%= render partial: 'login_message_active' %>
      </div>

      <%= render partial: 'login_message_preview' %>
    </div>
  <% end %>
</div>

app/views/admin/overview/toggle_login_message.js.erb
$('#login_message_active').html("<%= escape_javascript(render partial: 'login_message_active') %>");