config/routes.rb
GoTrack::Application.routes.draw do
  devise_for :user

  root to: 'home#index'

  get '/login', to: 'home#index'

  devise_scope :user do
    get '/user/sign_out', to: 'devise/sessions#destroy'
  end

  get '/set_ui_version' => 'application#set_ui_version', as: 'set_ui_version'
  get 'home' => 'home#index'
  get 'render_confirmation_modal' => 'application#render_confirmation_modal'

  get 'home/dispatch' => 'home#dispatch_device' # NOTE - dispatch needs to be changed to dispatch_device to avoid global name conflict
  post 'home/dispatch' => 'home#dispatch_device'

  get 'home/:action' => 'home'

  post '/home/act_as_if_account' => 'home#act_as_if_account'

  get '/geocoded_locations', to: 'locations#search_readings_location'

  resources :groups

  resources :devices, except: %i(new create show) do
    collection do
      post :search_devices
      post :choose_mt
    end
  end

  get 'reports' => 'reports#index'
  get 'reports/:action(/:id)' => 'reports', id: /\d+/, as: :action_reports

  resources :users, except: %i(show)

  resources :contact do
    collection do
      get :index
      post :thanks
    end
  end

  get 'settings' => 'settings#index'
  post 'settings' => 'settings#submit'

  get 'readings/:action(/:id)' => 'readings'

  namespace :api do
    post 'messages/send_messages' => 'messages#send_messages'
  end

  get 'admin_status/:action(/:id)' => 'admin_status'

  resources :scheduled_reports do
    member do
      get :download
    end
  end

  resources :geofences do
    collection do
      get :for_device
    end
  end

  get 'utils/:action(/:id)' => 'utils'
  get 'simulator' => 'simulator#index'
  get 'simulator/insert_reading' => 'simulator#insert_reading'

  resources :maintenances, except: %i(edit update) do
    member do
      post :reset
      get :reset
      post :complete
    end
  end

  namespace :admin do
    root to: 'overview#index'
    post :set_login_message, to: 'overview#set_login_message'
    get 'toggle_login_message', to: 'overview#toggle_login_message'

    resources :accounts, constraints: { id: /\d+/ } do
      collection do
        get '/search' => 'accounts#search'
      end
    end

    resources :device_profiles, constraints: { id: /\d+/ }

    resources :devices, constraints: { id: /\d+/ } do
      collection do
        get :digital_sensor_form
        get '/search' => 'devices#search'
        get '/clear_history' => 'devices#clear_history'
        get '/on_change_gateway_get_device_types' => 'devices#on_change_gateway_get_device_types'
      end
    end

    resources :users, except: [:show], constraints: { id: /\d+/ } do
      collection do
        get '/search' => 'users#search'
      end
    end
  end

  resources :devices do
    resources :test_readings, only: %i(new create)
  end

  resources :one_time_reports, only: %i(new create)
end

app/models/group.rb
class Group < ActiveRecord::Base
  include ApplicationHelper
  include DeviceOwner

  has_many :group_notifications
  has_many :geofences

  belongs_to :account
  has_many :devices, -> { where('devices.provision_status_id = ?', ProvisionStatus::STATUS_ACTIVE).order('name') }, dependent: :nullify, inverse_of: :group
  has_many :owned_devices, class_name: 'Device'

  scope :by_name, -> { order('groups.name ASC') }
  scope :for_user, lambda { |user| where('account_id IN (?)', user.accounts_ids).order('groups.name').includes(:devices) }

  validates_presence_of :name, :account_id, :image_value

  before_save :check_group_account_consistency

  after_update :clear_devices_from_cache, if: :max_speed_changed?

  def is_selected_for_notification(user)
    !GroupNotification.where('user_id = ? and group_id = ?', user.id, id).first.nil?
  end

  def get_readings_from_devices_for_rg
    Reading.where(id: devices.collect(&:last_gps_reading_id), location_id: nil)
  end

  def check_group_account_consistency
    self.devices.each do |device|
      if device.account_id != self.account_id
        device.update_attribute(:group_id, nil)
      end
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :authorize

  def index
    @groups = current_account.groups
  end

  def show
    load_group_by_id
  end

  def new
    set_device_and_groups
  end

  def edit
    load_group_by_id
    set_device_and_groups
  end

  def create
    @group = Group.new
    save_group
    if !validate_device_ids
      if @group.save
        update_devices
        flash[:success] = "Fleet " + @group.name + " was successfully added"
        redirect_to action: 'index'
      end
    else
      redirect_to action: "new"
    end

    set_device_and_groups
  end

  def update
    load_group_by_id

    @group = Group.find(params[:id])
    save_group
    if !validate_device_ids
      if @group.save
        Device.where('group_id = ?', @group.id).each do |device|
          device.group_id = nil
          device.save
        end
        first_set_icons_default
        update_devices
        flash[:success] = "Fleet #{@group.name} was updated successfully "
        redirect_to action: 'index'
      end
    else
      @group = Group.find(@group.id)
      flash[:group_name] = @group.name
      redirect_to action: 'edit', id: @group.id
    end

    set_device_and_groups
  end

  def destroy
    @group = Group.where('account_id = ?', current_account.id).find_by(id: params[:id])
    if @group
      flash[:success] = "Fleet #{@group.name} was deleted successfully "
      @group.destroy
      @group_devices = Device.where('group_id = ?', @group.id)
      @group_devices.each do |device|
        device.icon_id = '1'
        device.group_id = nil
        device.save
      end
    else
      flash[:error] = 'Invalid action'
    end
    redirect_to action: 'index'
  end

  private

  def save_group
    @group.name = params[:name]
    @group.max_speed = params[:max_speed]
    @group.image_value = params[:sel]
    @group.account_id = current_account.id
  end

  def first_set_icons_default
    @all_devices = Device.where('group_id = ? ', @group.id)
    @all_devices.each do |device|
      device.icon_id = '1'
      device.save
    end
    current_account.devices.where('group_id is NULL').each { |device| device.update_attribute(:icon_id, 1) }
  end

  def load_group_by_id
    if params[:id]
      @group = Group.find_by(id: params[:id], account_id: current_account.id)
      if @group
        flash[:group_name] = @group.name
        flash[:max_speed] = @group.max_speed
      else
        flash[:error] = 'Invalid action'
        redirect_to action: 'index'
      end
    end
  end

  def set_device_and_groups
    @devices = current_account.provisioned_devices
    @group_devices = current_account.provisioned_devices.where('group_id is not NULL')
  end

  def validate_device_ids
    if  params[:name] == "" || params[:select_devices].nil? || params[:select_devices].length == 0
      flash[:error] = ((@group.name == "") ? "Fleet name can't be blank <br/>" : "")
      flash[:error] << "You must select at least one device "
      flash[:group_name] = @group.name
      true
    end
  end

  def update_devices
    params[:select_devices].each do |device_id|
      device = Device.find(device_id)
      device.icon_id = params[:sel]
      device.group_id = @group.id
      device.save
    end
  end
end

app/views/groups/_form_content.html.erb
  <div class="page-header">
    <div class="page-header__title-container">
      <% if on_edit %>
        <div class="page-title">Edit Fleet</div>
      <% else %>
        <div class="page-title">Create a Fleet</div>
        <div class="new-fleet-form__main-description">
          Creating a fleet is simple. Just enter a fleet name, select an icon color, and specify the devices you want to associate with this fleet.
        </div>
      <% end %>
    </div>
  </div>

  <div class="new-fleet-form">
    <div class="new-fleet-form__cell">
      <div class="form-label form-label--title">Fleet Name</div>
      <input type="text" id="group_name" class="form-input form-input--full-width" name="name" placeholder="e.g. Name" value="<%= flash[:group_name]%>">
      <div class="form-label form-label--title new-fleet-form__icon-title">Select Icon</div>
      <div class="new-fleet-form__icon-list">
        <ul>
          <li>
            <%= image_tag('icons/blue_small.png', class: 'sel_icon__icon') %>
            <% if on_edit %>
              <input name="sel" <% if @group.try(:image_value) == 1 %>checked="checked" <%end%> type="radio"  value="1"  />
            <% else %>
              <input name="sel" checked="checked" type="radio" value="1" />
            <% end %>
          </li>

          <% (2..8).each do |i| %>
            <li>
              <%= render_icon(i) %>
              <input name="sel" type="radio" <% if @group.try(:image_value) == i %>checked="checked" <%end%>  value="<%= i %>"/>
            </li>
          <% end %>
        </ul>
      </div>
      <% if on_edit %>
        <div class="form-label form-label--title new-fleet-form__icon-title">Fleet Speed Limit</div>
        <div class="new-fleet-form__description">
          This setting applies to all devices in this fleet, and will override any other speed limits.
        </div>
        <input type="text" id="max_speed" name="max_speed" class="form-input form-input--small-width" value="<%= flash[:max_speed]%>" />
        <div class="new-fleet-form__description new-fleet-form__description--inline">MPH</div>
      <% end %>
    </div>

    <div class="new-fleet-form__cell">
      <div class="form-label form-label--title">Select Devices</div>
      <div class="new-fleet-form__description">
        Some devices may already be associated with another fleet.
        In this case the fleet name displays red after the device name.
        You can easily reassign any device to this fleet by clicking one or more checkboxes below.
      </div>
      <div class="new-fleet-form__select-devices__list-container">
        <ul class="new-fleet-form__select-devices__list" >
          <% @devices.each do |device| %>
            <li>
              <input type="checkbox" class="new-fleet-form__select-devices__checkbox" multiple name="select_devices[]"<% if device.group_id == @group.try(:id) %> checked="checked" <%end%> value="<%= device.id %>"></input>
              <div class="new-fleet-form__select-devices__device ellipsis" title="<%= device.name %>">
                <%= device.name %>
              </div>
              <% @group_devices.each do |group_device| %>
                <% if device.id == group_device.id %>
                  <div class="new-fleet-form__select-devices__fleet ellipsis">
                    <% if group_device.group.id != @group.try(:id) %>(<%= group_device.group.name%>)<% end %>
                  </div>
                <%end %>
              <%end %>
            </li>
          <%end %>
        </ul>
      </div>
    </div>
  </div>

app/views/groups/edit.html.erb
<%= render partial:"/layouts/flash_message" %>

<%= form_tag(group_path(@group), method: :put) do %>
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <input type="hidden" id="group_id" name="id" value="<%= @group.id %>">

    <%= render partial: 'form_content', locals: { on_edit: true } %>

  <div class="new-fleet-form__actions">
    <%= submit_tag "Update Fleet", class: 'button button--primary button--large button--inline button--right' %>
    <%= link_to 'Cancel', groups_path, class: "button button--secondary button--inline button--right" %>
  </div>
<% end %>

app/views/groups/index.html.erb
<%= render partial: '/layouts/flash_message' %>
<div class="fleets__content">

  <div class="page-header">
    <div class="page-header__title-container">
      <span class="page-title">Your Fleets (<%= @groups.size%> total)</span>
    </div>
    <% if controller.action_name == 'index' && !current_user.is_read_only? && !@groups.empty? %>
      <div class="page-header__action">
          <%= link_to('Add New Fleet', new_group_path, title: 'Create new fleet', class: "button button--primary button--large" )%>
      </div>
    <% end %>
  </div>

  <div class="fleets__description">
    Fleets are a great way to keep your devices organized.
    Creating a fleet is easy and allows you to quickly see which devices are associated with your fleet on the <a href="/home">overview screen</a>.
  </div>

  <table class='panel_table'>
    <tbody>
      <% if @groups.empty? && !current_user.is_read_only? %>
      <div class="fleets__empty-state empty-state">
        <div class="empty-state__logo">
          <i class="fa fa-truck" aria-hidden="true"></i>
        </div>
        <div class="empty-state__button-container">
          <%= link_to('Add New Fleet', new_group_path, title: 'Create new fleet', class: "button button--primary button--large" )%>
        </div>
        <div class="empty-state__text-container">
          <span class="empty-state__text-container__title">No fleets found. You can click the button above to create a new one.</span>
        </div>
      </div>
      <% else %>
        <% @groups.each do |group| %>
          <tr>
            <% if current_user.is_read_only? %>
              <td><%= group.name %></td>
            <% else %>
              <td class="fleets__name-cell">
                <%= group.name %>
              </td>
              <td class="fleets__edit-cell">
                <div class="table-actions">
                  <%= link_to edit_group_path(group), title: 'Edit this fleet' do %>
                    <i class="fa fa-pencil link-icon" aria-hidden="true"></i>
                  <% end %>
                  <%= link_to group_path(group.id), method: :delete, title: 'Delete this fleet', data: { confirm: 'Are you sure you want to delete this fleet?' } do %>
                    <i class="fa fa-trash link-icon"></i>
                  <% end %>
                </div>
              </td>
            <% end %>
          </tr>
      <% end %>
    </tbody>
  </table>
</div>
<% end %>

app/views/groups/new.html.erb
<%= render partial: "/layouts/flash_message" %>

<%= form_tag(groups_path, method: :post) do %>
  <%= render partial: 'form_content', locals: { on_edit: false } %>
  <div class="new-fleet-form__actions">
    <%= submit_tag "Create Fleet", class: 'button button--primary button--large button--inline button--right' %>
    <%= link_to 'Cancel', groups_path, class: "button button--secondary button--inline button--right" %>
  </div>
<% end %>

<script type="text/javascript">
	window.onload = function() {
		document.getElementById("group_name").focus();
	}
</script>